export const BUS_BEGIN="BUS_BEGIN";
export const BUS_SUCCESS="BUS_SUCCESS";
export const BUS_ERROR="BUS_ERROR";

 export const BUS_ADD_BEGIN="BUS_ADD_BEGIN";
 export const BUS_ADD_SUCCESS="BUS_ADD_SUCCESS";
 export const BUS_ADD_ERROR="BUS_ADD_ERROR";


 export const BUS_EDIT_BEGIN="BUS_ADD_BEGIN";
 export const BUS_EDIT_SUCCESS="BUS_ADD_SUCCESS";
 export const BUS_EDIT_ERROR="BUS_ADD_ERROR";


 export const BUS_DELETE_BEGIN="BUS_ADD_BEGIN";
 export const BUS_DELETE_SUCCESS="BUS_ADD_SUCCESS";
 export const BUS_DELETE_ERROR="BUS_ADD_ERROR";
